### Neste arquivo notebook, vamos descrever diversas funções da biblioteca OpenCV, com exemplos, para processamento digital de imagens, focando somente em contornos.

______________________

## Função `findContours()`

####    A função `findContours()` da OpenCV usa o algoritmo de detecção de contornos de Suzuki e Abe, baseado no algoritmo de rasterização de varredura de Moore. Esse algoritmo é amplamente conhecido como algoritmo de "cadeia" ou "cadeia de contorno". O algoritmo começa varrendo a imagem da esquerda para a direita e de cima para baixo. Ele segue os pixels do objeto (pixels brancos numa imagem binária) e registra as coordenadas desses pixels.

______________________


## Parâmetros:

#### `image` fonte, uma imagem de canal único em 8 bits. Pixels não nulos são tratados como 1's. Pixels zero permanecem 0's, então a imagem é tratada como binária.

#### `contours` contornos detectados. Cada contorno é armazenado como um vetor de pontos.

#### `hierarchy` vetor de saída opcional, contendo informações sobre a topologia da imagem. Tem tantos elementos quanto o número de contornos. Para cada i-ésimo contorno contours[i], os elementos hierarchy[i][0], hierarchy[i][1], hierarchy[i][2] e hierarchy[i][3] são definidos como índices baseados em 0 nos contornos do próximo e do contorno anterior no mesmo nível hierárquico, o primeiro contorno filho e o contorno pai, respectivamente. Se para o contorno i não houver próximos, anteriores, pai ou contornos aninhados, os elementos correspondentes de hierarchy[i] serão negativos.

#### `mode` modo de recuperação de contornos, veja RetrievalModes.

#### `method` método de aproximação de contornos, veja ContourApproximationModes.

#### `offset` deslocamento opcional pelo qual cada ponto do contorno é deslocado. Isso é útil se os contornos forem extraídos da região de interesse (ROI) da imagem e, em seguida, analisados no contexto da imagem inteira.

______________________

## Detecção de contornos:

#### `cv.CHAIN_APPROX_NONE` todos os pontos de limite são armazenados.
#### `cv.CHAIN_APPROX_SIMPLE` remove todos os pontos redundantes e comprime o contorno, economizando memória.

______________________

## Recuperação do contorno:

#### `cv2.RETR_EXTERNAL` para recuperar apenas os contornos externos,
#### `cv2.RETR_LIST` para recuperar todos os contornos sem hierarquia,

______________________

## Extração de contornos:

#### `cv.RETR_EXTERNAL` recupera apenas os contornos externos extremos. Define hierarquia[i][2]=hierarquia[i][3]=-1 para todos os contornos.

####  `cv.RETR_LIST` recupera todos os contornos sem estabelecer nenhuma relação hierárquica.

####  `cv.RETR_CCOMP` recupera todos os contornos e os organiza em uma hierarquia de dois níveis. No nível superior, estão os contornos externos. No segundo nível, existem contornos dos internos. Se houver outro contorno dentro de um componente conectado, ele ainda será colocado no nível superior.

#### `cv.RETR_TREE` recupera todos os contornos e reconstrói uma hierarquia completa de contornos aninhados.

______________________

In [3]:
# Utilizando find contours
import cv2

# Conversão para escala cinza
image = cv2.imread('camisa.png')
img_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('Imagem Cinza', img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Threshold da imagem
ret, thresh = cv2.threshold(img_gray, 200, 255, cv2.THRESH_BINARY)
cv2.imshow('Imagem Binaria', thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Contornos
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_NONE)

______________________

## Função `drawContours()`

#### Utilizada para desenhar um contorno nas imagens RGB identificadas. Requer 4 parâmetros e tem outros opcionais, descritos abaixo:

______________________

## Parâmetros:

#### `image` imagem RGB de entrada.

#### `contours` o vetor de contornos retornados pela função.

#### `contourIdx` vetor com as coordenadas de cada contorno. Usando este argumento, você pode especificar a posição do índice desta lista, indicando exatamente qual ponto de contorno você deseja desenhar. Fornecer um valor negativo irá desenhar todos os pontos de contorno.

#### `color` a cor desejada para desenhar o contono.

#### `thickness` a espessura do contorno. Valores negativos vão resultar em preenchimento da figura.

#### `lineType` conectividade da linha.

#### `hierarchy` informação opcional sobre a hierarquia. É necessária apenas se você quiser desenhar apenas alguns dos contornos.

#### `maxLevel` nível máximo para contornos desenhados. Se for 0, apenas o contorno especificado é desenhado. Se for 1, a função desenha o(s) contorno(s) e todos os contornos aninhados. Se for 2, a função desenha os contornos, todos os contornos aninhados, todos os contornos aninhados aos aninhados, e assim por diante. Este parâmetro só é considerado quando há hierarquia disponível.

#### `offset` Parâmetro opcional de deslocamento do contorno. Desloca todos os contornos desenhados pelo deslocamento especificado=(dx,dy).
______________________

## Exemplos:

`findContours()` | `cv2.RETR_TREE | cv2.CHAIN_APPROX_NONE`


In [137]:
image_copy = image.copy()

cv2.drawContours(image=image_copy,contours=contours, contourIdx=-1, color=(0,255,0), thickness=2, lineType=cv2.LINE_AA)

print("Quantidade de objetos: " + str(len(contours)))
cv2.imshow('Desenhando contornos usando CHAIN_APPROX_NONE', image_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

Quantidade de objetos: 8


`findContours()` | `cv2.RETR_TREE | cv2.CHAIN_APPROX_SIMPLE`

In [138]:
contours2, hierarchy2 = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_SIMPLE)

image_copy = image.copy()

cv2.drawContours(image=image_copy,contours=contours2, contourIdx=-1, color=(0,255,0), thickness=2, lineType=cv2.LINE_AA)

print("Quantidade de objetos: " + str(len(contours2)))
cv2.imshow('Desenhando contornos usando CHAIN_APPROX_SIMPLE', image_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

Quantidade de objetos: 8


______________________

## Hierarquia

* #### Se existem objetos dentro de outros objetos, existe uma hierarquia dos contornos. A hierarquia pode ser representada por [Next, Previous, First_Child, Parent]

* #### Next: Indica o próximo contorno em uma imagem, que está no mesmo nível hierárquico. Quando este valor é -1, indica que o próximo contorno não está no mesmo nivel hierarquico.
* #### Previous: Indica o contorno anterior no mesmo nível hierárquico. Se este valor é -1, é porque o contorno anterior da hierarquia não está no mesmo nivel.
* #### First-child: Indica o primeiro contorno filho do contorno que estamos considerando atualmente. O valor -1 indica que não tem nenhum filho (contorno interno)
* #### Parent: Indica a posição de índice do contorno pai para o contorno atual. -1 indica que não tem contorno pai (externo)

______________________ 
### Cenários comuns:

* #### Contornos independentes: Se o valor de Next for -1 e o valor de Previous também for - 1, significa que o contorno atual não tem contornos irmãos no mesmo nível hierárquico.
* #### Contornos aninhados: Se o valor de First_Child for diferente de -1, isso significa que o contorno atual tem pelo menos um contorno filho. O valor de First_Child indica o índice do primeiro contorno filho.

* #### Contornos externos: Se o valor de Parent for -1, significa que o contorno atual não tem um contorno pai. Esses são os contornos mais externos na hierarquia.

* #### Contornos conectados: Através da hierarquia, é possível identificar contornos que estão conectados uns aos outros. Ao percorrer a hierarquia, você pode acessar os contornos vizinhos, pais ou filhos de um determinado contorno.
______________________
### Exemplos: 

#### `cv2.RETR_TREE`

In [139]:
import numpy as np

# Hierarquia de contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos
    image_copy = image.copy()

    # Desenha todos os contornos encontrados na imagem
    cv2.drawContours(image=image_copy, contours=contours, contourIdx=-1, color=(0, 255, 0), thickness=2, lineType=cv2.LINE_AA)

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Obtém o retângulo delimitador para o contorno
        x, y, w, h = cv2.boundingRect(c)

        # Cria o texto para exibir informações sobre o contorno e a hierarquia
        texto = "Contorno: " + str(i) + " " + np.array2string(hierarchy[0][i])

        # Desenha o texto na imagem
        cv2.putText(image_copy, texto, (x, y + 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    print("Matriz de hierarquias:\n ", hierarchy)

    # Exibe a imagem com os contornos desenhados e os textos adicionados
    cv2.imshow("Hierarquia", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

Quantidade de objetos: 8
Matriz de hierarquias:
  [[[-1 -1  1 -1]
  [ 2 -1 -1  0]
  [ 4  1  3  0]
  [-1 -1 -1  2]
  [-1  2  5  0]
  [-1 -1  6  4]
  [-1 -1  7  5]
  [-1 -1 -1  6]]]


______________________

## Resumo da hierarquia 

* #### Contorno 0: Um contorno externo sem filhos.
* #### Contorno 1: Um contorno externo com um filho (contorno 2).
* #### Contorno 2: Filho do contorno 1, sem filhos próprios.
* #### Contorno 3: Um contorno externo com um filho (contorno 4).
* #### Contorno 4: Filho do contorno 3, com um filho (contorno 5).
* #### Contorno 5: Filho do contorno 4, com um filho (contorno 6).
* #### Contorno 6: Filho do contorno 5, sem filhos próprios.
______________________

### Contornos externos

#### `cv2.RETR_EXTERNAL`

In [140]:
# Aplicação do ‘threshold’ binário
ret, thresh = cv2.threshold(img_gray, 200, 255, cv2.THRESH_BINARY_INV)

# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_NONE)

# Hierarquia de contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos
    image_copy = image.copy()

    # Desenha todos os contornos encontrados na imagem
    cv2.drawContours(image=image_copy, contours=contours, contourIdx=-1, color=(0, 255, 0), thickness=2, lineType=cv2.LINE_AA)

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Obtém o retângulo delimitador para o contorno
        x, y, w, h = cv2.boundingRect(c)

        # Cria o texto para exibir informações sobre o contorno e a hierarquia
        texto = "Contorno: " + str(i) + " " + np.array2string(hierarchy[0][i])

        # Desenha o texto na imagem
        cv2.putText(image_copy, texto, (x, y + 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com os contornos desenhados e os textos adicionados
    cv2.imshow("Contornos externos", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Quantidade de objetos: 3


______________________

## Momento

* ####  A função `cv2.moments` calcula os momentos de um contorno ou de uma imagem binária. Os momentos são úteis para a análise de formas, pois podem ser usados para calcular propriedades como área, centroide e outras características geométricas de um objeto.

* #### Cálculo dos Momentos: A função `cv2.moments` é usada para calcular os momentos de cada contorno.
* #### Cálculo da Área e Centroide: Usando os momentos, a área (M['m00']) e o centroide (cx e cy) são calculados.
* #### Exibição das Propriedades: A área e o centroide são adicionados ao texto exibido na imagem para cada contorno.
______________________

In [141]:
# Leitura da imagem
image = cv2.imread('random_shapes.png')

# Conversão para escala de cinza
img_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Aplicação do ‘threshold’ binário
ret, thresh = cv2.threshold(img_gray, 200, 255, cv2.THRESH_BINARY)

# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_NONE)

# Hierarquia de contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos
    image_copy = image.copy()

    # Desenha todos os contornos encontrados na imagem
    cv2.drawContours(image=image_copy, contours=contours, contourIdx=-1, color=(0, 255, 0), thickness=2, lineType=cv2.LINE_AA)

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Obtém o retângulo delimitador para o contorno
        x, y, w, h = cv2.boundingRect(c)

        # Cria o texto para exibir informações sobre o contorno e a hierarquia
        texto = "Contorno: " + str(i) + " " + np.array2string(hierarchy[0][i])

        # Desenha o texto na imagem
        cv2.putText(image_copy, texto, (x, y + 10), font, fontScale, color, thickness, cv2.LINE_AA)
        
        '''
        Cálculo dos momentos, área e centróide
        '''
        # Calcula os momentos do contorno
        M = cv2.moments(c)

        # Calcula a área e o centroide do contorno
        if M["m00"] != 0:
            cx = int(M["m10"] / M["m00"])
            cy = int(M["m01"] / M["m00"])
        else:
            cx, cy = 0, 0
        
        # Adiciona a área e o centroide ao texto
        texto_momentos = f"Area: {M['m00']} Centroid: ({cx}, {cy})"
        cv2.putText(image_copy, texto_momentos, (x, y + 30), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com os contornos desenhados e os textos adicionados
    cv2.imshow("Momento", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Quantidade de objetos: 10


______________________
## Área e perímetro

* #### A função `cv2.contourArea` calcula a área de um contorno, enquanto `cv2.arcLength` calcula o perímetro (comprimento) de um contorno.
* #### Cálculo da Área: area = `cv2.contourArea(c)` calcula a área de cada contorno.
* #### Cálculo do Perímetro: perimetro = `cv2.arcLength(c, True)` calcula o perímetro de cada contorno.
* #### Exibição das Propriedades: A área, o perímetro e o centroide são adicionados ao texto exibido na imagem para cada contorno.
______________________

In [142]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_NONE)

# Hierarquia de contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos
    image_copy = image.copy()

    # Desenha todos os contornos encontrados na imagem
    cv2.drawContours(image=image_copy, contours=contours, contourIdx=-1, color=(0, 255, 0), thickness=2, lineType=cv2.LINE_AA)

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Obtém o retângulo delimitador para o contorno
        x, y, w, h = cv2.boundingRect(c)

        # Calcula a área do contorno
        area = cv2.contourArea(c)

        # Calcula o perímetro do contorno
        perimetro = cv2.arcLength(c, True)

        # Cria o texto para exibir a área e o perímetro do contorno
        texto = f"Area: {area:.2f} Perimetro: {perimetro:.2f}"

        # Desenha o texto na imagem
        cv2.putText(image_copy, texto, (x, y + 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com os contornos desenhados e os textos adicionados
    cv2.imshow("Area e perimetro", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Quantidade de objetos: 10


______________________

## Aproximação de contorno

* #### A função `cv2.approxPolyDP` aproxima um contorno usando um polígono com menos vértices baseado na precisão especificada pelo parâmtro `epsilon`.
* #### O contorno original é desenhado em verde ((0, 255, 0)). 
* #### O contorno aproximado é desenhado em azul ((255, 0, 0)).

______________________

In [143]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_NONE)

# Hierarquia de contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos e aproximações
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Aproximação do contorno usando epsilon = 1% do perímetro do contorno
        epsilon = 0.02 * cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, epsilon, True)

        # Desenha o contorno original na imagem
        cv2.drawContours(image_copy, [c], -1, (0, 255, 0), 2)

        # Desenha o contorno aproximado na imagem
        cv2.drawContours(image_copy, [approx], -1, (255, 0, 0), 2)

        # Obtém o retângulo delimitador para o contorno aproximado
        x, y, w, h = cv2.boundingRect(approx)
        
        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))
    
    # Exibe a imagem com os contornos originais e aproximados desenhados e os textos adicionados
    cv2.imshow("Contornos e Aproximacoes", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Quantidade de objetos: 10


________________

## Convex Hull

* #### O convex hull é a menor forma convexa que envolve todos os pontos de um contorno
* #### Cálculo do convex hull: Utilizamos `cv2.convexHull(c)` para calcular o convex hull de cada contorno.
* #### Desenho do convex hull: O convex hull é desenhado em vermelho ((255, 0, 0)) enquanto o contorno original é desenhado em verde ((0, 255, 0)).
* #### Cálculo da área e perímetro do convex hull: São calculados e exibidos para o convex hull.
________________



In [144]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos e o convex hull
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Calcula o convex hull do contorno
        hull = cv2.convexHull(c)

        # Desenha o contorno original na imagem
        cv2.drawContours(image_copy, [c], -1, (0, 255, 0), 2)

        # Desenha o convex hull na imagem
        cv2.drawContours(image_copy, [hull], -1, (255, 0, 0), 2)

        # Calcula a área e o perímetro do convex hull
        area = cv2.contourArea(hull)
        perimetro = cv2.arcLength(hull, True)

        # Obtém o retângulo delimitador para o convex hull
        x, y, w, h = cv2.boundingRect(hull)

        # Cria o texto para exibir a área e o perímetro do convex hull
        texto = f"Area: {area:.2f} Perimetro: {perimetro:.2f}"

        # Desenha o texto na imagem
        cv2.putText(image_copy, texto, (x, y + 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com os contornos e o convex hull desenhados e os textos adicionados
    cv2.imshow("Convex Hull", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Quantidade de objetos: 10


____________

## Retângulos delimitadores

* #### Retângulo Delimitador Horizontal (Straight Bounding Rectangle): O retângulo que é paralelo aos eixos x e y da imagem. Usamos `cv2.boundingRect(c)` para obter as coordenadas do retângulo que é paralelo aos eixos da imagem e desenhamos com `cv2.rectangle`.
* #### Retângulo Delimitador Rotacionado (Rotated Bounding Rectangle): O retângulo que pode estar rotacionado e é o mínimo retângulo que pode envolver o contorno. Usamos `cv2.minAreaRect(c)` para obter o retângulo mínimo rotacionado que envolve o contorno. Convertendo o retângulo rotacionado para pontos de contorno com `cv2.boxPoints(rect)` e desenhamos com `cv2.drawContours`.
* #### Calculamos a área e o perímetro do retângulo rotacionado e desenhamos esses valores na imagem.
____________


In [145]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os retângulos
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Retângulo delimitador horizontal (straight bounding rectangle)
        x, y, w, h = cv2.boundingRect(c)
        cv2.rectangle(image_copy, (x, y), (x + w, y + h), (0, 255, 0), 2)

        # Retângulo delimitador rotacionado (rotated bounding rectangle)
        rect = cv2.minAreaRect(c)
        box = cv2.boxPoints(rect)
        box = np.array(box, dtype=np.int32)
        cv2.drawContours(image_copy, [box], 0, (255, 0, 0), 2)

        # Calcula a área e o perímetro do retângulo rotacionado
        area = cv2.contourArea(box)
        perimetro = cv2.arcLength(box, True)

        # Cria o texto para exibir a área e o perímetro do retângulo rotacionado
        texto = f"Area: {area:.2f} Perimetro: {perimetro:.2f}"

        # Desenha o texto na imagem
        cv2.putText(image_copy, texto, (x, y - 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com os retângulos delimitadores desenhados e os textos adicionados
    cv2.imshow("Bounding Rectangles", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Quantidade de objetos: 10


_______________

## Círculo mínimo envolvente

* #### A função `cv2.minEnclosingCircle`. Esse círculo é o menor círculo que pode envolver todo o contorno.
* #### Usamos `cv2.minEnclosingCircle(c)` para encontrar o centro e o raio do círculo mínimo que pode envolver o contorno.
* #### Usamos `cv2.circle(image_copy, center, radius, (255, 0, 0), 2)` para desenhar o círculo em azul ((255, 0, 0)).
* #### A área do círculo é calculada como  pi × radius ^ 2.
* #### O perímetro é calculado como 2 × pi × radius.
_______________



In [146]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os círculos
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Calcula o círculo mínimo envolvente do contorno
        (x, y), radius = cv2.minEnclosingCircle(c)
        center = (int(x), int(y))
        radius = int(radius)

        # Desenha o círculo mínimo envolvente
        cv2.circle(image_copy, center, radius, (255, 0, 0), 2)

        # Calcula a área e o perímetro do círculo mínimo envolvente
        area = np.pi * (radius ** 2)
        perimetro = 2 * np.pi * radius

        # Cria o texto para exibir a área e o perímetro do círculo
        texto = f"Area: {area:.2f} Perimetro: {perimetro:.2f}"

        # Desenha o texto na imagem
        cv2.putText(image_copy, texto, (center[0] - radius, center[1] - radius - 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com os círculos mínimos envolventes desenhados e os textos adicionados
    cv2.imshow("Minimum Enclosing Circles", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

Quantidade de objetos: 10


________________

## Elipse

* #### A função `cv2.fitEllipse`. Esta função ajusta uma elipse ao contorno fornecido e retorna o centro, os eixos e o ângulo da elipse.
* #### Utilizamos `cv2.fitEllipse(c)` para ajustar uma elipse ao contorno c. Esta função retorna uma tupla contendo o centro da elipse, os tamanhos dos eixos e o ângulo de rotação.
* #### Usamos `cv2.ellipse(image_copy, ellipse, (255, 0, 0), 2)` para desenhar a elipse em azul ((255, 0, 0)).
* #### O texto inclui o centro da elipse, os tamanhos dos eixos e o ângulo de rotação. Este texto é posicionado próximo ao centro da elipse.
* #### Verificamos se o contorno tem pelo menos 5 pontos com len(c) >= 5, pois é necessário um número mínimo de pontos para ajustar uma elipse.
________________

In [147]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar as elipses
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Verifica se o contorno tem pelo menos 5 pontos (necessário para ajustar uma elipse)
        if len(c) >= 5:
            # Ajusta uma elipse ao contorno
            ellipse = cv2.fitEllipse(c)

            # Desenha a elipse ajustada na imagem
            cv2.ellipse(image_copy, ellipse, (255, 0, 0), 2)

            # Cria o texto para exibir as características da elipse
            center = (int(ellipse[0][0]), int(ellipse[0][1]))
            axes = (int(ellipse[1][0]), int(ellipse[1][1]))
            angle = int(ellipse[2])
            texto = f"Centro: {center} Eixos: {axes} Angulo: {angle}"

            # Desenha o texto na imagem
            cv2.putText(image_copy, texto, (center[0] - 100, center[1] - 20), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com as elipses desenhadas e os textos adicionados
    cv2.imshow("Fitting Ellipses", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Quantidade de objetos: 10


__________

## Ajuste de linha

* #### A função `cv2.fitLine` ajusta uma linha aos pontos do contorno e retorna a equação da linha em forma de vetor.
* #### Usamos `cv2.fitLine(c, cv2.DIST_L2, 0, 0.01, 0.01)` para ajustar uma linha aos pontos do contorno c. A função retorna o vetor da linha [vx, vy] e o ponto de origem (x, y).
* #### Calculamos os pontos finais da linha para garantir que ela cubra toda a imagem. O ponto inicial é calculado usando o vetor vx e vy deslocado para fora da imagem e o ponto final é calculado deslocando-se dentro da imagem.
* #### Usamos `cv2.line(image_copy, start_point, end_point, (255, 0, 0), 2)` para desenhar a linha ajustada em azul ((255, 0, 0)).
* #### O texto inclui o vetor da linha e o ponto de origem, e é desenhado na imagem próximo ao topo.
* #### Verificamos se o contorno tem pelo menos 2 pontos com len(c) >= 2, 
__________

In [148]:


# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar as linhas
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Verifica se o contorno tem pelo menos 2 pontos (necessário para ajustar uma linha)
        if len(c) >= 2:
            # Ajusta uma linha aos pontos do contorno
            [vx, vy, x, y] = cv2.fitLine(c, cv2.DIST_L2, 0, 0.01, 0.01)

            # Converte os vetores para float e extrai os valores escalares
            vx, vy, x, y = vx[0], vy[0], x[0], y[0]

            # Calcula os pontos finais da linha para desenhar
            rows, cols = image_copy.shape[:2]
            start_point = (int(x - vx * 1000), int(y - vy * 1000))
            end_point = (int(x + vx * (rows + 1000)), int(y + vy * (cols + 1000)))

            # Desenha a linha ajustada na imagem
            cv2.line(image_copy, start_point, end_point, (255, 0, 0), 2)

            # Cria o texto para exibir a equação da linha
            texto = f"Line: [{vx:.2f}, {vy:.2f}] Origin: ({x:.2f}, {y:.2f})"

            # Desenha o texto na imagem
            cv2.putText(image_copy, texto, (10, 30 + i * 20), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com as linhas ajustadas e os textos adicionados
    cv2.imshow("Fitting Lines", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Quantidade de objetos: 10


_________

## Aspect ratio

* #### O aspect ratio (razão de aspecto) de um contorno é a razão entre a largura e a altura do retângulo delimitador do contorno. Ele pode ser útil para entender a forma dos objetos detectados na imagem.
* #### A razão de aspecto é calculada como float(w) / float(h), onde w é a largura e h é a altura do retângulo delimitador obtido com `cv2.boundingRect`.
* #### Usamos cv2.rectangle para desenhar o retângulo delimitador ao redor do contorno na imagem.
* #### O texto que exibe a razão de aspecto é desenhado próximo ao topo do retângulo delimitador.
* #### Verificamos se h é diferente de zero antes de calcular a razão de aspecto para evitar divisão por zero.
_________

In [149]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os retângulos e textos
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Obtém o retângulo delimitador para o contorno
        x, y, w, h = cv2.boundingRect(c)

        # Calcula a razão de aspecto
        aspect_ratio = float(w) / float(h) if h != 0 else 0

        # Desenha o retângulo delimitador na imagem
        cv2.rectangle(image_copy, (x, y), (x + w, y + h), (0, 255, 0), 2)

        # Cria o texto para exibir a razão de aspecto
        texto = f"Aspect Ratio: {aspect_ratio:.2f}"

        # Desenha o texto na imagem
        cv2.putText(image_copy, texto, (x, y - 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com os retângulos delimitadores e os textos adicionados
    cv2.imshow("Aspect Ratio", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Quantidade de objetos: 10


__________

## Extent

* #### O extent (extensão) de um contorno é a razão entre a área do contorno e a área do retângulo delimitador (bounding box) ao redor do contorno. Ele é útil para determinar quão "compacto" ou "espalhado" é um contorno em relação ao seu retângulo delimitador.
* #### A área do contorno é obtida com `cv2.contourArea(c)`. A área do retângulo delimitador é calculada como w * h, onde w é a largura e h é a altura do retângulo. O extent é então calculado como contour_area / bounding_box_area.
* #### Usamos `cv2.rectangle` para desenhar o retângulo delimitador ao redor do contorno na imagem.
* #### O texto que exibe o extent é desenhado próximo ao topo do retângulo delimitador.
* #### Verificamos se a área do retângulo delimitador é diferente de zero antes de calcular o extent para evitar divisão por zero.
_________

In [150]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os retângulos e textos
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Obtém a área do contorno
        contour_area = cv2.contourArea(c)

        # Obtém o retângulo delimitador para o contorno
        x, y, w, h = cv2.boundingRect(c)
        bounding_box_area = w * h

        # Calcula o extent
        extent = contour_area / bounding_box_area if bounding_box_area != 0 else 0

        # Desenha o retângulo delimitador na imagem
        cv2.rectangle(image_copy, (x, y), (x + w, y + h), (0, 255, 0), 2)

        # Cria o texto para exibir o extent
        texto = f"Extent: {extent:.2f}"

        # Desenha o texto na imagem
        cv2.putText(image_copy, texto, (x, y - 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com os retângulos delimitadores e os textos adicionados
    cv2.imshow("Extent", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

Quantidade de objetos: 10


________

## Solidity

* #### Solidity é uma métrica que indica a "compactação" de um contorno, comparando a área do contorno com a área do seu convex hull (caso o contorno não seja convexo). A fórmula para calcular a solidez é: área do contorno / área do convex hull
* #### A solidez é útil para identificar contornos que são próximos de formas convexas. Valores próximos de 1 indicam que o contorno é mais próximo de uma forma convexa, enquanto valores menores indicam contornos mais "esburacados".
* #### Usamos `cv2.convexHull(c)` para obter o convex hull do contorno c. Calculamos a área do convex hull com `cv2.contourArea(convex_hull)`.
* #### A solidez é calculada como contour_area / convex_hull_area.
* #### Usamos `cv2.drawContours` para desenhar tanto o contorno original quanto o convex hull na imagem. O convex hull é desenhado em azul ((255, 0, 0)) e o contorno original em verde ((0, 255, 0)).
* #### O texto que exibe a solidez é desenhado próximo ao topo do retângulo delimitador do contorno.
* #### Verificamos se a área do convex hull é diferente de zero antes de calcular a solidez para evitar divisão por zero.

______________



In [151]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos e textos
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Obtém a área do contorno
        contour_area = cv2.contourArea(c)

        # Obtém o convex hull do contorno
        convex_hull = cv2.convexHull(c)
        convex_hull_area = cv2.contourArea(convex_hull)

        # Calcula a solidez
        solidity = contour_area / convex_hull_area if convex_hull_area != 0 else 0

        # Desenha o convex hull na imagem
        cv2.drawContours(image_copy, [convex_hull], 0, (255, 0, 0), 2)

        # Desenha o contorno original na imagem
        cv2.drawContours(image_copy, [c], 0, (0, 255, 0), 2)

        # Cria o texto para exibir a solidez
        texto = f"Solidity: {solidity:.2f}"

        # Desenha o texto na imagem
        x, y, w, h = cv2.boundingRect(c)
        cv2.putText(image_copy, texto, (x, y - 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com os contornos e convex hulls desenhados, além dos textos adicionados
    cv2.imshow("Solidity", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

Quantidade de objetos: 10



__________
## Diâmetro equivalente

* #### O diâmetro equivalente de um contorno é o diâmetro de um círculo que tem a mesma área que o contorno. Em outras palavras, é o diâmetro de um círculo que teria a mesma área que o contorno em questão. Esse valor é útil para entender o tamanho geral de um contorno e pode ajudar na análise de formas e tamanhos dos objetos detectados.
* #### Fórmula: 2 x (raiz_quadrada (área do contorno / pi))
* #### A área do contorno é obtida com `cv2.contourArea(c)`. O diâmetro equivalente é calculado como 2 * np.sqrt(contour_area / np.pi).
* #### Usamos `cv2.drawContours` para desenhar o contorno na imagem.
* #### O texto que exibe o diâmetro equivalente é desenhado próximo ao topo do retângulo delimitador do contorno.
* #### Verificamos se a área do contorno é maior que zero antes de calcular o diâmetro equivalente para evitar cálculos inválidos.
__________

In [152]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos e textos
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Obtém a área do contorno
        contour_area = cv2.contourArea(c)

        # Calcula o diâmetro equivalente
        if contour_area > 0:
            equivalent_diameter = 2 * np.sqrt(contour_area / np.pi)
        else:
            equivalent_diameter = 0

        # Desenha o contorno na imagem
        cv2.drawContours(image_copy, [c], 0, (0, 255, 0), 2)

        # Cria o texto para exibir o diâmetro equivalente
        texto = f"Diametro Equivalente: {equivalent_diameter:.2f}"

        # Desenha o texto na imagem
        x, y, w, h = cv2.boundingRect(c)
        cv2.putText(image_copy, texto, (x, y - 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com os contornos desenhados e os textos adicionados
    cv2.imshow("Diametro Equivalente", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Quantidade de objetos: 10


___________

## Orientação

* #### A orientação de um contorno refere-se ao ângulo de rotação da elipse que melhor se ajusta ao contorno. Esse ângulo é medido em relação ao eixo horizontal da imagem. A orientação é útil para determinar a direção principal de um objeto dentro da imagem.
* #### A função `cv2.fitEllipse(c)` ajusta uma elipse ao contorno c. Ela retorna uma tupla contendo o centro da elipse, os eixos e o ângulo de rotação da elipse.
* #### Usamos `cv2.ellipse` para desenhar a elipse ajustada na imagem.
* #### O texto que exibe a orientação (ângulo de rotação da elipse) é desenhado próximo ao topo do retângulo delimitador do contorno.
* #### O ajuste da elipse requer pelo menos 5 pontos no contorno. Se o contorno tiver menos de 5 pontos, a elipse não pode ser ajustada, então o código verifica isso antes de tentar ajustar a elipse.
___________

In [153]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos e textos
    image_copy = image.copy()

    # Configurações para o texto a ser exibido
    font = cv2.FONT_HERSHEY_SIMPLEX
    fontScale = 0.6
    color = (0, 0, 255)
    thickness = 1
    i = 0

    for c in contours:
        # Aproximação do contorno por uma elipse
        if len(c) >= 5:  # Número mínimo de pontos para ajustar uma elipse
            # Ajusta a elipse ao contorno
            ellipse = cv2.fitEllipse(c)
            center, axes, angle = ellipse

            # Desenha a elipse ajustada na imagem
            cv2.ellipse(image_copy, ellipse, (255, 0, 0), 2)

            # Cria o texto para exibir a orientação
            texto = f"Orientacao: {angle:.2f} graus"

            # Desenha o texto na imagem
            x, y, w, h = cv2.boundingRect(c)
            cv2.putText(image_copy, texto, (x, y - 10), font, fontScale, color, thickness, cv2.LINE_AA)

        # Incrementa o contador de contornos
        i += 1

    # Exibe a quantidade de contornos encontrados
    print("Quantidade de objetos: " + str(len(contours)))

    # Exibe a imagem com as elipses desenhadas e os textos adicionados
    cv2.imshow("Orientacao", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

Quantidade de objetos: 10


______________

## Máscara e pontos de pixel

* #### Máscara e pontos de píxel são técnicas úteis para trabalhar com contornos e regiões de interesse em imagens. 
* #### A máscara é uma imagem binária onde a região correspondente ao contorno é preenchida com 1 (ou 255) e o resto é 0.
* #### Os pontos de pixel da máscara que pertencem ao contorno são extraídos para análise adicional.
* #### `np.zeros_like(img_gray, dtype=np.uint8)` cria uma máscara preta (todos os valores são 0). `cv2.drawContours(mask, [c], -1, 255, thickness=cv2.FILLED)` desenha o contorno na máscara, preenchendo a região correspondente com 255.
* #### `np.column_stack(np.where(mask > 0))` retorna as coordenadas dos pixels que são diferentes de zero na máscara (ou seja, pertencem ao contorno).
* #### `cv2.circle` é usado para desenhar pontos na imagem original para visualização, onde cada ponto é um pixel pertencente ao contorno.
* #### `cv2.imshow` exibe a máscara do contorno e a imagem com contornos e pontos de pixel desenhados.
______________

In [154]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos
    image_copy = image.copy()

    # Para cada contorno encontrado
    for i, c in enumerate(contours):
        # Cria uma máscara do mesmo tamanho que a imagem original
        mask = np.zeros_like(img_gray, dtype=np.uint8)

        # Preenche a máscara com o contorno
        cv2.drawContours(mask, [c], -1, 255, thickness=cv2.FILLED)

        # Extrai os pontos de pixel pertencentes ao contorno
        points = np.column_stack(np.where(mask > 0))

        # Desenha o contorno na imagem original
        cv2.drawContours(image_copy, [c], 0, (0, 255, 0), 2)

        # Exibe a máscara
        cv2.imshow(f"Mascara do Contorno {i}", mask)

        # Exibe os pontos de pixel
        print(f"Pontos de Pixel para o Contorno {i}:")
        print(points)

        for point in points:
            cv2.circle(image_copy, (point[1], point[0]), 1, (255, 0, 0), -1)

    # Exibe a imagem com os contornos desenhados
    cv2.imshow("Contornos e Pontos de Pixel", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

Pontos de Pixel para o Contorno 0:
[[420 405]
 [420 406]
 [420 407]
 ...
 [534 365]
 [534 366]
 [534 367]]
Pontos de Pixel para o Contorno 1:
[[414 559]
 [414 560]
 [414 561]
 ...
 [491 585]
 [491 586]
 [491 587]]
Pontos de Pixel para o Contorno 2:
[[388  95]
 [388  96]
 [388  97]
 ...
 [470 150]
 [470 151]
 [470 152]]
Pontos de Pixel para o Contorno 3:
[[284 216]
 [284 217]
 [284 218]
 ...
 [355 260]
 [355 261]
 [355 262]]
Pontos de Pixel para o Contorno 4:
[[202 426]
 [202 427]
 [202 428]
 ...
 [395 400]
 [395 401]
 [395 402]]
Pontos de Pixel para o Contorno 5:
[[176 593]
 [176 594]
 [176 595]
 ...
 [365 593]
 [365 594]
 [365 595]]
Pontos de Pixel para o Contorno 6:
[[139 343]
 [139 344]
 [139 345]
 ...
 [215 324]
 [215 325]
 [215 326]]
Pontos de Pixel para o Contorno 7:
[[ 79 155]
 [ 79 156]
 [ 79 157]
 ...
 [238 130]
 [238 131]
 [238 132]]
Pontos de Pixel para o Contorno 8:
[[ 64 417]
 [ 64 418]
 [ 64 419]
 ...
 [154 440]
 [154 441]
 [154 442]]
Pontos de Pixel para o Contorno 9:
[[

_________________

## Valor máximo, mínimo e suas localizações

* #### Para encontrar o valor máximo e mínimo dentro de uma máscara binária e suas localizações, você pode usar as seguintes etapas:
* #### Criar a Máscara do Contorno: A máscara binária é uma imagem onde a região correspondente ao contorno é preenchida com 255 (ou 1) e o restante é 0.
* #### Encontrar os Valores Máximo e Mínimo: `cv2.minMaxLoc` pode ser usado para encontrar o valor mínimo e máximo e suas localizações em uma matriz.
* #### `np.zeros_like(img_gray, dtype=np.uint8)` cria uma máscara preta. `cv2.drawContours(mask, [c], -1, 255, thickness=cv2.FILLED)` desenha o contorno na máscara.
* #### `cv2.minMaxLoc(mask)` retorna o valor mínimo e máximo na máscara e suas localizações.
* #### `cv2.circle` é usado para desenhar círculos vermelhos e verdes nas localizações dos valores máximos e mínimos, respectivamente.
* #### `cv2.imshow` exibe a imagem com os contornos e os pontos máximos e mínimos destacados.
______________

##  Média da cor e a média da intensidade

* #### Use a máscara binária para isolar a região de interesse.
* #### Para imagens em escala de cinza, a média da intensidade é a média dos valores dos pixels na região da máscara.
* #### Para imagens coloridas, calcule a média dos valores de cor (BGR) para os pixels dentro da máscara. 
* #### `np.zeros_like(img_gray, dtype=np.uint8)` cria uma máscara preta. `cv2.drawContours(mask, [c], -1, 255, thickness=cv2.FILLED)` desenha o contorno na máscara, preenchendo a região correspondente com 255.
* #### `cv2.mean(img_gray, mask=mask)[0]` calcula a média dos valores dos pixels na imagem em escala de cinza dentro da máscara.
* #### `cv2.mean(image, mask=mask)[:3]` calcula a média dos valores dos canais B, G e R (coloridos) dentro da máscara. O [:3] remove o valor do canal alfa, se presente.
* #### `cv2.drawContours` desenha os contornos na imagem original. `cv2.putText` adiciona texto à imagem com a média da intensidade e cor.
* #### `cv2.imshow` exibe a imagem com contornos e informações adicionais.

______________


In [155]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos
    image_copy = image.copy()

    for i, c in enumerate(contours):
        # Cria uma máscara do mesmo tamanho que a imagem original
        mask = np.zeros_like(img_gray, dtype=np.uint8)

        # Preenche a máscara com o contorno
        cv2.drawContours(mask, [c], -1, 255, thickness=cv2.FILLED)

        # Calcula a média da intensidade para a imagem em escala de cinza
        mean_intensity = cv2.mean(img_gray, mask=mask)[0]

        # Calcula a média da cor para a imagem colorida
        mean_color = cv2.mean(image, mask=mask)[:3]  # Desconsidera o canal alfa se houver

        # Encontra os valores máximo e mínimo e suas localizações
        min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(mask)

        # Desenha o contorno na imagem original
        cv2.drawContours(image_copy, [c], 0, (0, 255, 0), 2)

        # Marca os pontos máximo e mínimo na máscara
        cv2.circle(image_copy, max_loc, 5, (0, 0, 255), -1)  # Vermelho para valor máximo
        cv2.circle(image_copy, min_loc, 5, (255, 0, 0), -1)  # Azul para valor mínimo

        # Adiciona texto para exibir média e valores
        font = cv2.FONT_HERSHEY_SIMPLEX
        fontScale = 0.6
        color = (0, 0, 255)
        thickness = 1
        x, y, w, h = cv2.boundingRect(c)
        

        # Exibe os valores calculados
        print(f"Contorno {i}:")
        print(f"  Média da Intensidade: {mean_intensity:.2f}")
        print(f"  Média da Cor (BGR): {tuple(map(int, mean_color))}")
        print(f"  Valor Mínimo: {min_val:.2f} na localização {min_loc}")
        print(f"  Valor Máximo: {max_val:.2f} na localização {max_loc}")

    # Exibe a imagem com os contornos e os textos adicionados
    cv2.imshow("Mascara com Media e Min/Max Valores", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Contorno 0:
  Média da Intensidade: 255.00
  Média da Cor (BGR): (255, 255, 255)
  Valor Mínimo: 0.00 na localização (0, 0)
  Valor Máximo: 255.00 na localização (405, 420)
Contorno 1:
  Média da Intensidade: 255.00
  Média da Cor (BGR): (255, 255, 255)
  Valor Mínimo: 0.00 na localização (0, 0)
  Valor Máximo: 255.00 na localização (559, 414)
Contorno 2:
  Média da Intensidade: 255.00
  Média da Cor (BGR): (255, 255, 255)
  Valor Mínimo: 0.00 na localização (0, 0)
  Valor Máximo: 255.00 na localização (95, 388)
Contorno 3:
  Média da Intensidade: 254.96
  Média da Cor (BGR): (254, 254, 254)
  Valor Mínimo: 0.00 na localização (0, 0)
  Valor Máximo: 255.00 na localização (216, 284)
Contorno 4:
  Média da Intensidade: 255.00
  Média da Cor (BGR): (255, 255, 255)
  Valor Mínimo: 0.00 na localização (0, 0)
  Valor Máximo: 255.00 na localização (426, 202)
Contorno 5:
  Média da Intensidade: 255.00
  Média da Cor (BGR): (255, 255, 255)
  Valor Mínimo: 0.00 na localização (0, 0)
  Valor Máxi

______________
## Pontos extremos

* #### Use a função `cv2.boundingRect` para obter o retângulo delimitador, mas para pontos mais precisos, use diretamente os pontos do contorno.
* #### Marque esses pontos na imagem para visualização.
* #### `np.zeros_like(img_gray, dtype=np.uint8)` cria uma máscara preta. `cv2.drawContours(mask, [c], -1, 255, thickness=cv2.FILLED)` desenha o contorno na máscara, preenchendo a região correspondente com 255.
* #### `leftmost = tuple(c[c[:, :, 0].argmin()][0])` encontra o ponto mais à esquerda.
* #### `rightmost = tuple(c[c[:, :, 0].argmax()][0])` encontra o ponto mais à direita.
* #### `topmost = tuple(c[c[:, :, 1].argmin()][0])` encontra o ponto mais alto.
* #### `bottommost = tuple(c[c[:, :, 1].argmax()][0])` encontra o ponto mais baixo.
* #### `cv2.circle` é usado para marcar os pontos extremos com diferentes cores.
* #### `cv2.putText` adiciona texto à imagem com os pontos extremos. `cv2.imshow` exibe a imagem com os contornos e pontos extremos.
______________



In [156]:
# Encontrar contornos com o modo cv2.RETR_EXTERNAL
contours, _ = cv2.findContours(image=thresh, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)

# Verifica se foram encontrados contornos
if len(contours) == 0:
    print("Nenhum contorno foi encontrado.")
else:
    # Cria uma cópia da imagem original para desenhar os contornos
    image_copy = image.copy()

    for i, c in enumerate(contours):
        # Cria uma máscara do mesmo tamanho que a imagem original
        mask = np.zeros_like(img_gray, dtype=np.uint8)

        # Preenche a máscara com o contorno
        cv2.drawContours(mask, [c], -1, 255, thickness=cv2.FILLED)

        # Encontrar os pontos extremos
        leftmost = tuple(c[c[:, :, 0].argmin()][0])
        rightmost = tuple(c[c[:, :, 0].argmax()][0])
        topmost = tuple(c[c[:, :, 1].argmin()][0])
        bottommost = tuple(c[c[:, :, 1].argmax()][0])

        # Desenha o contorno na imagem original
        cv2.drawContours(image_copy, [c], 0, (0, 255, 0), 2)

        # Marca os pontos extremos na imagem
        cv2.circle(image_copy, leftmost, 5, (255, 0, 0), -1)  # Azul para o ponto mais à esquerda
        cv2.circle(image_copy, rightmost, 5, (0, 255, 0), -1)  # Verde para o ponto mais à direita
        cv2.circle(image_copy, topmost, 5, (0, 0, 255), -1)    # Vermelho para o ponto mais alto
        cv2.circle(image_copy, bottommost, 5, (0, 255, 255), -1)  # Amarelo para o ponto mais baixo

        # Adiciona texto para exibir os pontos extremos
        font = cv2.FONT_HERSHEY_SIMPLEX
        fontScale = 0.3
        color = (0, 0, 255)
        thickness = 1

        # Ajusta a posição do texto para não sobrepor os contornos
        text_offset = 20
        text_positions = [
            (leftmost[0] + 10, leftmost[1] - text_offset),
            (rightmost[0] + 10, rightmost[1] - text_offset),
            (topmost[0] + 10, topmost[1] - text_offset),
            (bottommost[0] + 10, bottommost[1] + text_offset)
        ]
        text_labels = [
            f"L: {leftmost}",
            f"R: {rightmost}",
            f"T: {topmost}",
            f"B: {bottommost}"
        ]

        for pos, label in zip(text_positions, text_labels):
            cv2.putText(image_copy, label, pos, font, fontScale, color, thickness, cv2.LINE_AA)

        # Exibe os valores calculados
        print(f"Contorno {i}:")
        print(f"  Ponto mais à esquerda: {leftmost}")
        print(f"  Ponto mais à direita: {rightmost}")
        print(f"  Ponto mais alto: {topmost}")
        print(f"  Ponto mais baixo: {bottommost}")

    # Exibe a imagem com os contornos e os pontos extremos marcados
    cv2.imshow("Contornos com Pontos Extremos", image_copy)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Contorno 0:
  Ponto mais à esquerda: (242, 488)
  Ponto mais à direita: (427, 442)
  Ponto mais alto: (405, 420)
  Ponto mais baixo: (345, 534)
Contorno 1:
  Ponto mais à esquerda: (498, 429)
  Ponto mais à direita: (620, 440)
  Ponto mais alto: (559, 414)
  Ponto mais baixo: (523, 491)
Contorno 2:
  Ponto mais à esquerda: (88, 391)
  Ponto mais à direita: (269, 429)
  Ponto mais alto: (95, 388)
  Ponto mais baixo: (137, 470)
Contorno 3:
  Ponto mais à esquerda: (132, 326)
  Ponto mais à direita: (262, 355)
  Ponto mais alto: (216, 284)
  Ponto mais baixo: (255, 355)
Contorno 4:
  Ponto mais à esquerda: (353, 287)
  Ponto mais à direita: (445, 253)
  Ponto mais alto: (426, 202)
  Ponto mais baixo: (392, 395)
Contorno 5:
  Ponto mais à esquerda: (515, 287)
  Ponto mais à direita: (598, 354)
  Ponto mais alto: (593, 176)
  Ponto mais baixo: (583, 365)
Contorno 6:
  Ponto mais à esquerda: (280, 154)
  Ponto mais à direita: (371, 209)
  Ponto mais alto: (343, 139)
  Ponto mais baixo: (281,

______________

## Extração de contornos nvia WebCam

* #### O código usa a webcam para capturar vídeo em tempo real.
* #### Para cada frame capturado: Desfoque: Aplica um desfoque Gaussian para reduzir o ruído e suavizar a imagem. Conversão de Cor: Converte a imagem de BGR (cor padrão do OpenCV) para HSV (espaço de cor mais adequado para filtragem de cores).
* #### Máscara de Cor: Cria uma máscara que destaca apenas as áreas da imagem que estão dentro do intervalo de cor AZUL especificado.
* #### Encontra os contornos nas áreas da máscara que são azuis.
* #### Desenha os contornos encontrados sobre o frame original.
* #### Mostra duas janelas: uma com o frame original e contornos desenhados, e outra com a máscara.
______________


In [157]:
# Abre a captura de vídeo da webcam
cap = cv2.VideoCapture(0)

while True:
    # Captura frame a frame
    _, frame = cap.read()

    # Aplica o desfoque para reduzir o ruído
    blurred_frame = cv2.GaussianBlur(frame, (5, 5), 0)

    # Converte o frame para o espaço de cor HSV
    hsv = cv2.cvtColor(blurred_frame, cv2.COLOR_BGR2HSV)

    # Define o intervalo para a cor azul
    lower_blue = np.array([38, 86, 0])
    upper_blue = np.array([121, 255, 255])

    # Cria uma máscara com base no intervalo de cor azul
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    # Encontra os contornos na máscara
    contours, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

    # Desenha os contornos no frame original
    for contour in contours:
        cv2.drawContours(frame, contour, -1, (0, 255, 0), 3)

    # Exibe o frame com contornos e a máscara
    cv2.imshow("Frame", frame)
    cv2.imshow("Mask", mask)

    # Encerra o loop ao pressionar a tecla ESC
    key = cv2.waitKey(1)
    if key == 27:
        break

# Libera a captura e fecha as janelas
cap.release()
cv2.destroyAllWindows()


______________

## Um pouco mais sobre métodos de aproximação

* #### cv2.CHAIN_APPROX_NONE: armazena todos os pontos de contorno, sem realizar nenhuma simplificação. Pode resultar em uma grande quantidade de pontos de contorno, ocupando mais memória e aumentando o tempo de processamento.
* #### cv2.CHAIN_APPROX_SIMPLE: realiza uma simplificação do contorno, eliminando os pontos redundantes e mantendo apenas os pontos extremos que definem a forma do contorno. 
* #### cv2.CHAIN_APPROX_TC89_L1 e cv2.CHAIN_APPROX_TC89_KCOS: Esses métodos são variantes do método Douglas-Peucker para aproximação de contorno. Eles usam o algoritmo de simplificação de contorno de Douglas-Peucker, que realiza uma simplificação adaptativa, mantendo apenas os pontos essenciais do contorno com base em uma tolerância definida. Esses métodos são mais precisos em manter a forma do contorno original em comparação com o cv2.CHAIN_APPROX_SIMPLE, mas também podem resultar em mais pontos de contorno.
______________